[package]
name = "gw2_location_logger"
version = "1.0.0-beta"
edition = "2018"

[dependencies]
mumblelink_reader = "0.3.2"
clap = "3.0.0-beta.4"
csv = "1.1"
serde = { version = "1", features = ["derive"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1